Add -d option to mini_align and assess_assembly to select minimap2 alignment preset. Remove -T (trimming) option in assess_assembly and related ref_seqs_from_bam.py script. Redirect echo messages to stderr. Add accumulation of errors over a number of chunks (set by -a option in summary_from_stats.py and assess_assembly) to get better stats. Update versions of minimap2, samtools, bcftools, bedtools in Makefile to the most recent ones.

diff --git a/scripts/mini_align b/scripts/mini_align
--- a/scripts/mini_align
+++ b/scripts/mini_align
@@ -11,6 +11,7 @@ Align fastq/a formatted reads to a genome using minimap2.
     -i  fastq/a input reads (required).
     -I  split index every ~NUM input bases (default: 16G, this is larger
         than the usual minimap2 default).
+	-d  set the minimap2 preset, e.g. map-ont, asm5, asm10, asm20 [default: map-ont]
     -f  force recreation of index file.
     -a  aggressively extend gaps (sets -A1 -B2 -O2 -E1 for minimap2).
     -P  filter to only primary alignments (i.e. run samtools view -F 2308).
@@ -26,14 +27,15 @@ Align fastq/a formatted reads to a genome using minimap2.
     -s  fill cs(=long) tag.
     -X  only create reference index files.
     -x  log all commands before running.
-    -M  match score 
+    -M  match score
     -S  mismatch score
-    -O  open gat penalty
+    -O  open gap penalty
     -E  extend gap penalty."
 
 
 PREFIX="reads"
-ALIGN_OPTS="-x map-ont"
+minimap_PRESET="map-ont"
+ALIGN_OUTPUT_OPTS="--secondary=no"  # Holder for --MD --cs=long --secondary=no options
 INDEX_SIZE="16G"
 THREADS=1
 FILTER="-F 2308"
@@ -48,34 +50,36 @@ csmd_set=0
 aflag=false
 aparamflag=false
 xflag=false
-MATCH_SCORE="2"
-MISMATCH_SCORE="4"
-GAP_OPEN="4,24"
-GAP_EXTEND="2,1"
+#MATCH_SCORE="2"
+#MISMATCH_SCORE="4"
+#GAP_OPEN="4,24"
+#GAP_EXTEND="2,1"
+ALIGN_PARAMETERS=""  # match, mismatch, gap options combined
 
-while getopts ':hr:i:I:M:S:O:E:fPAymsnp:ac:t:Xx' option; do
+while getopts ':hr:i:d:I:M:S:O:E:fPAymsnp:ac:t:Xx' option; do
   case "$option" in
     h  ) echo "$usage" >&2; exit;;
     r  ) rflag=true; REFERENCE=$OPTARG;;
     i  ) iflag=true; INPUT=$OPTARG;;
+	d  ) minimap_PRESET=$OPTARG;;
     I  ) INDEX_SIZE=$OPTARG;;
     f  ) FORCE_INDEX=true;;
-    P  ) filter_set=$(($filter_set + 1)); echo "-P option is deprecated";;
-    A  ) filter_set=$(($filter_set + 1)); FILTER="";;
-    y  ) filter_set=$(($filter_set + 1)); FILTER="-F 260";;
-    m  ) csmd_set=$(($csmd_set + 1)); ALIGN_OPTS="${ALIGN_OPTS} --MD";;
-    s  ) csmd_set=$(($csmd_set + 1)); ALIGN_OPTS="${ALIGN_OPTS} --cs=long";;
+    P  ) filter_set=$(($filter_set + 1)); echo "-P option is deprecated" >&2;;
+    A  ) filter_set=$(($filter_set + 1)); FILTER=""; ALIGN_OUTPUT_OPTS=${ALIGN_OUTPUT_OPTS/--secondary=no/} ;;
+	y  ) filter_set=$(($filter_set + 1)); FILTER="-F 260";;
+    m  ) csmd_set=$(($csmd_set + 1)); ALIGN_OUTPUT_OPTS="${ALIGN_OUTPUT_OPTS} --MD";;
+    s  ) csmd_set=$(($csmd_set + 1)); ALIGN_OUTPUT_OPTS="${ALIGN_OUTPUT_OPTS} --cs=long";;
     n  ) SORT="${SORT} -n";;
     p  ) PREFIX=$OPTARG;;
-    a  ) aflag=true; MATCH_SCORE="1"; MISMATCH_SCORE="2"; GAP_OPEN="2"; GAP_EXTEND="1";;
+    a  ) aflag=true; ALIGN_PARAMETERS="-A 1 -B 2 -O 2 -E 1";;
     c  ) CHUNK=$OPTARG;;
     t  ) THREADS=$OPTARG;;
     X  ) ONLY_INDEX=true;;
     x  ) xflag=true;;
-    M  ) aparamflag=true; MATCH_SCORE=$OPTARG;;
-    S  ) aparamflag=true; MISMATCH_SCORE=$OPTARG;;
-    O  ) aparamflag=true; GAP_OPEN=$OPTARG;;
-    E  ) aparamflag=true; GAP_EXTEND=$OPTARG;;
+    M  ) aparamflag=true; ALIGN_PARAMETERS="${ALIGN_PARAMETERS} -A ${OPTARG}";;
+    S  ) aparamflag=true; ALIGN_PARAMETERS="${ALIGN_PARAMETERS} -B ${OPTARG}";;
+    O  ) aparamflag=true; ALIGN_PARAMETERS="${ALIGN_PARAMETERS} -O ${OPTARG}";;
+    E  ) aparamflag=true; ALIGN_PARAMETERS="${ALIGN_PARAMETERS} -E ${OPTARG}";;
     \? ) echo "Invalid option: -${OPTARG}." >&2; exit 1;;
     :  ) echo "Option -$OPTARG requires an argument." >&2; exit 1;;
   esac
@@ -84,7 +88,7 @@ shift $(($OPTIND - 1))
 
 if [ "$filter_set" -gt 1 ]; then
     echo "$usage" >&2;
-    echo "More than one filtering setting [-A, -P, -y] was specified; these are mutually incompatible (-P is deprecated)." >&2;
+	echo "More than one filtering setting [-A, -P, -y] was specified; these are mutually incompatible (-P is deprecated)." >&2;
     exit 1;
 fi
 
@@ -116,31 +120,33 @@ if $xflag; then
   set -x;
 fi
 
-minimap_exts=('.mmi' '.fai')
-num_minimap_exts=${#minimap_exts[@]}
-missing=0
-for ext in "${minimap_exts[@]}"; do
-  minimap_index="${REFERENCE}${ext}"
-  if ${FORCE_INDEX}; then
-    echo "Removing previous index file ${minimap_index}"
-    rm -rf "${minimap_index}"
-  fi
-  if [[ ! -e "${minimap_index}" ]]; then
-    ((missing+=1))
-  fi
-done;
 
-if [ "$missing" -eq 0 ]; then
-  echo "Found minimap files." >&2
-elif [ "$missing" -eq "$num_minimap_exts" ]; then
-  echo "Constructing minimap index." >&2
-  samtools faidx "${REFERENCE}"
-  minimap2 -I "${INDEX_SIZE}" ${ALIGN_OPTS} -d "${REFERENCE}.mmi" "${REFERENCE}" \
-      || { echo "Indexing draft failed"; exit 1; }
+# Check if the indices are present and create them if not
+# fai index
+fai_index="${REFERENCE}.fai"
+if ${FORCE_INDEX}; then
+	echo "Removing previous fai index file ${fai_index}" >&2
+	rm -rf "${fai_index}"
+fi
+if [[ ! -e "${fai_index}" ]]; then
+	echo "Creating fai index file ${fai_index}" >&2
+	samtools faidx "${REFERENCE}"
 else
-  echo "Missing ${missing} index files. Clean up any files named
-${REFERENCE}<EXT> where <EXT> is one of ${minimap_exts[*]}." >&2
-  exit 1;
+	echo "Using the existing fai index file ${fai_index}" >&2
+fi
+
+# mmi (minimap2) index - specific to the preset used
+mmi_index="${REFERENCE}.${minimap_PRESET}.mmi"
+if ${FORCE_INDEX}; then
+	echo "Removing previous mmi index file ${mmi_index}" >&2
+	rm -rf "${mmi_index}"
+fi
+if [[ ! -e "${mmi_index}" ]]; then
+	echo "Creating mmi index file ${mmi_index}" >&2
+	minimap2 -I "${INDEX_SIZE}" -x ${minimap_PRESET} -d "${mmi_index}" "${REFERENCE}" \
+      || { echo "Indexing draft failed" >&2; exit 1; }
+else
+	echo "Using the existing mmi index file ${mmi_index}" >&2
 fi
 
 if ${ONLY_INDEX}; then
@@ -150,14 +156,13 @@ fi
 if [ "$CHUNK" != "" ]; then
   echo "Splitting input into ${CHUNK} chunks." >&2
   split_fastx "${INPUT}" "${INPUT}.chunks" "${CHUNK}" \
-      || { echo "Failed to split input into chunks."; exit 1; }
+      || { echo "Failed to split input into chunks." >&2; exit 1; }
   INPUT="${INPUT}.chunks"
 fi
 
-minimap2 ${ALIGN_OPTS} -t "${THREADS}" -a "${REFERENCE}.mmi" "${INPUT}" \
-  -A "${MATCH_SCORE}" -B "${MISMATCH_SCORE}" -O "${GAP_OPEN}" -E "${GAP_EXTEND}" |
+minimap2 -x ${minimap_PRESET} ${ALIGN_OUTPUT_OPTS} ${ALIGN_PARAMETERS} -t "${THREADS}" -a "${mmi_index}" "${INPUT}" |
   samtools view -@ "${THREADS}" -T "${REFERENCE}" ${FILTER} -bS - |
-  samtools sort -@ "${THREADS}" ${SORT} -l 9 -o "${PREFIX}.bam" - \
-    || { echo "Alignment pipeline failed."; exit 1; }
+  samtools sort -@ "${THREADS}" ${SORT} -o "${PREFIX}.bam" - \
+    || { echo "Alignment pipeline failed." >&2; exit 1; }
 samtools index -@ "${THREADS}" "${PREFIX}.bam" "${PREFIX}.bam.bai" \
-    || { echo "Failed to index alignment file."; exit 1; }
+    || { echo "Failed to index alignment file." >&2; exit 1; }
